# Generated by Django 4.0.4 on 2022-05-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
