# Generated by Django 4.0.4 on 2022-05-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MBA',
        ),
        migrations.DeleteModel(
            name='MCA',
        ),
    ]
