# Generated by Django 4.0.4 on 2022-05-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_mca_mba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
