# Generated by Django 4.0.4 on 2022-05-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mca',
            name='category',
        ),
        migrations.DeleteModel(
            name='MBA',
        ),
        migrations.DeleteModel(
            name='MCA',
        ),
    ]
