# Generated by Django 4.0.4 on 2022-05-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_branch_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
