# Generated by Django 4.0.4 on 2022-05-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_students_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='category',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
