# Generated by Django 4.0.4 on 2022-05-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_branche_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
