# Generated by Django 4.0.4 on 2022-05-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='vote',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
