# Generated by Django 4.0.4 on 2022-05-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_vote_student_vote_name_vote_roll_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
