# Generated by Django 4.0.4 on 2022-05-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='Student',
        ),
        migrations.AddField(
            model_name='vote',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='roll_no',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
