# Generated by Django 4.0.4 on 2022-05-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='score',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
